### ISSUE TITLE
Cocoapods?

### ISSUE THREAD

**Issue by jlalvarez18** [totocaster/CDFInitialsAvatar#2]
Any plans on adding this to Cocoapods?

**Comment by totocaster** [comment]
Yes, will add. Thanks.

**Comment by romanr** [comment]
Please do!

**Comment by claudiumatei** [comment]
subscribe

**Comment by totocaster** [comment]
`1.0.4` published as `CDFInitialsAvatar` Pod. Sorry it took so long.
